# Generated by Django 4.2.7 on 2025-05-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_warehouse_remove_inventory_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
