# Generated by Django 4.2.7 on 2025-05-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='Mức tồn kho tối thiểu'),
        ),
    ]
